name: Yarn audit

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

on:
  pull_request:
    branches: ["develop"]

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/checkout/commit/50fbc622fc4ef5163becd7fab6573eac35f8462e
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # pin@v1

      # https://github.com/actions/setup-node/commit/f1f314fca9dfce2769ece7d933488f076716723e
      - name: Setup Node.js
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # pin@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@dknmz"

      - name: Run yarn audit
        run: yarn audit
        id: audit
        continue-on-error: true
        env:
          CI: true

      # https://cli.github.com/manual/gh_search_issues
      - name: Check for open issues
        id: issues
        if: ${{ steps.audit.outcome == 'failure' }}
        run: |
          count=$(gh search issues --state open "is:issue in:title [GENERATED ISSUE] yarn audit found security issues" | jq -r '.total_count')
          if [ "$count" -gt 0 ]; then
            echo "::set-output name=has-open-issues::true"
          else
            echo "::set-output name=has-open-issues::false"
          fi
      # https://cli.github.com/manual/gh_issue_create
      - name: Create issue
        if: ${{ steps.issues.outputs.has-open-issues == 'false' }}
        run: |
          echo "No open issues with the same title found. Creating a new issue."          
          issue_title="[GENERATED ISSUE] yarn audit found security issues"
          issue_body="Yarn audit found security issues"
          issue_labels="dependencies,security"
          gh issue create --title "$issue_title" --body "$issue_body" --label "$issue_labels"
