name: Yarn audit

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
on:
  pull_request:
    branches: ['main']

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Run yarn audit
        run: yarn audit
        id: audit
        continue-on-error: true
        env:
          CI: true
          
      - name: Check for open issues
        id: issues
        run: |
          count=$(gh search issues --state open "is:issue in:title [GENERATED ISSUE] yarn audit found security issues" | jq -r '.total_count')
          if [ "$count" -gt 0 ]; then
            echo "::set-output name=has-open-issues::true"
          else
            echo "::set-output name=has-open-issues::false"
          fi
          
      - name: Create issue
        if: ${{ steps.issues.outputs.has-open-issues == 'false' }}
        run: |
          echo "No open issues with the same title found. Creating a new issue."          
          issue_title="[GENERATED ISSUE] yarn audit found security issues"
          issue_body="Yarn audit command failed"
          issue_labels="security,dependencies"
          gh issue create --title "$issue_title" --body "$issue_body" --label "$issue_labels"
